### ISSUE TITLE
Improvement: iOS Statusbar Color

### ISSUE THREAD

**Issue by danielsogl** [fluster/fluster-app#4]
From the Apple human interface guidelines:

A dark status bar works well above light-colored content and a light status bar works well above dark-colored content.

https://developer.apple.com/design/human-interface-guidelines/ios/bars/status-bars/

Because of the Fluster colors, a light/white statusbar should look better then the actual black one.

**Comment by peterpeterparker** [comment]
@danielsogl sorry, maybe a dumb question, but where did you notice a status bar on iOS?

just tested on simulated iPhone 8 and iPad and in both case my statusbar was transparent

which property did you meant? https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-statusbar/

sorry for the dumb question, I'm missing something for sure

<img width="613" alt="capture d ecran 2018-09-13 a 16 10 26" src="https://user-images.githubusercontent.com/16886711/45493757-c342fc00-b76f-11e8-8943-b3ec2f0285f0.png">

**Comment by danielsogl** [comment]
I mean the color of the clock and batterie indicator. I missed to explain that better.

**Comment by peterpeterparker** [comment]
My gosh why I didn't noticed that earlier, it's so ugly to have the text in black 🙈

Well spotted 👍 

Fixed f6659ae088029ca994ee77cd8fdde509e6fd0abe
