### ISSUE TITLE
Improvement: Login Page Tablet screenshots

### ISSUE THREAD

**Issue by danielsogl** [fluster/fluster-app#8]
I noticed that the login page app screenshots are not that good drained (I used my iPad Pro 10.5). They should be replaced with higher resolution images or screenshots from the tablet version of the app.

**Comment by peterpeterparker** [comment]
@danielsogl cool input. I don't want to ask too much, but did you maybe took a screenshot? I don't own an iPad, that would help

**Comment by danielsogl** [comment]
Here you have it:
![32f7f74a-183b-4f0c-9ffa-e4c003a5f1fc](https://user-images.githubusercontent.com/15234844/45487548-96361f80-b756-11e8-873e-a6b56dde0f72.png)

As you can see the card text looks not well on that screen size.

**Comment by peterpeterparker** [comment]
@danielsogl thx agree the text looks on the screenshot aren't good at all. I'm so paranoiac about app size, I compress every resources ;)

P.S.: You are testing the app powered by Ionic v3. The one of this repo powered by Ionic v4 is in production, right now, only as a PWA. I plan to send this brand new app to Apple for verification in the next days, probable v5.0.0-beta.5

P.P.S.: Easy to notice the difference, with v4 I use now the `<ion-button shape="round"/>`, they are so nice ;)

**Comment by peterpeterparker** [comment]
Follow-up task https://github.com/fluster/fluster-app/issues/9

**Comment by peterpeterparker** [comment]
Improved in 483f7c714cf7343cad4c771a096e2aa77b815e22
